[project]
name = "GumBOTchi"
version = "0.1.0"
description = "Discord Bot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.9.2",
    "pandas>=2.2.3",
    "py-cord[voice]>=2.6.1",
    "pymongo>=4.10.1",
    "yt-dlp>=2024.9.27",
]
